# Generated by Django 5.1.5 on 2025-01-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='teamadmin',
            field=models.BooleanField(default=False),
        ),
    ]
