# Generated by Django 5.1.5 on 2025-02-01 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_change_ticket', models.BigIntegerField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('first_level_support_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_level_support', to='teams.team')),
                ('second_level_support_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_level_support', to='teams.team')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipments.site')),
            ],
        ),
    ]
