# Generated by Django 5.1.5 on 2025-02-01 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('teams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Comment Type',
                'verbose_name_plural': 'Comment Types',
            },
        ),
        migrations.CreateModel(
            name='TicketAcknowledgmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Acknowledgment Status',
                'verbose_name_plural': 'Acknowledgment Statuses',
            },
        ),
        migrations.CreateModel(
            name='TicketStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_started', models.DateTimeField()),
                ('issue_resolved', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('owner_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketstatustype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('comment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.commenttype')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRequestedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketacknowledgmentstatus')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tickets', to='teams.team')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_teams', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Requested Team',
                'verbose_name_plural': 'Requested Teams',
            },
        ),
        migrations.CreateModel(
            name='TicketsAffectedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(db_column='equipment_id', on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
                ('ticket', models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Tickets Affected Equipment',
                'verbose_name_plural': 'Tickets Affected Equipment',
            },
        ),
    ]
